export const SET_COMPANIES = "SET_COMPANIES";
export const ADD_COMPANY = "ADD_COMPANY";
export const SET_SEARCH_PARAMETER = "SET_SEARCH_PARAMETER";
export const SET_DESCENDING_ORDER = "SET_DESCENDING_ORDER";
export const HANDLE_UPVOTE = "HANDLE_UPVOTE";
